language: ruby
rvm:
- 2.1.10
script:
- RAILS_ENV=test bundle exec rake db:migrate && bundle exec rspec
before_script:
- psql -c 'create database bikewise_test' -U postgres
env:
  global:
    secure: iTxhupaRvHb6/PnacSp47jV42U/slDTwGRwghHVBkKLoUmaEHoWB+qBhHDk2q3YVWnOEs4eQ7DjhBWkdq1OUEvnxall3UAop3576eDlQOFdaOXnazlWlXJDfIPdzlkVXtO6LQUJK5FC5b8/ntpasN7O8g6550AssynCbcGAdbw4=
